## PyTorch 

- Scientific computing package  
- Replacement for NumPy to use the power of GPus 
- Deep learning research platform that provides maximum flexibility and speed 




In [1]:
import torch 

### Tensors 


PyTorch uses **Tensor** as its core data structure, which is similar to Numpy array. Tensors provide acceleration of various mathematical operations. These operations when carried out in a large number in Deep Learning make a huge difference in speed.

Tensor is simply a fancy name given to matrices. A scalar value is represented by a 0-dimensional Tensor. Similarly a column/row matrix using a 1-D Tensor and so on. 

#### Creating Tensors

In [11]:
# Create a tensor with just ones 

a = torch.ones(5)
print(a)


# Create a tensor with just zeros 

b = torch.zeros(5)
print(b)


# Create a tensor with custom values

c = torch.Tensor([1, 3, 5, 7, 9])
print(c)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])
tensor([1., 3., 5., 7., 9.])


In [21]:
# Tensors of Higher dimension: 

# torch.zeros(Rows, Columns) 
d = torch.zeros(3,2)
print(d)


e = torch.ones(2,5)
print(e)


f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)


# 3D Tensor
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [22]:
# find out shape of the tensor 

print(e.shape)

print(f.shape)
 
print(g.shape)


torch.Size([2, 5])
torch.Size([2, 2])
torch.Size([2, 2, 2])


#### Accessing element in a 1D Tensor aka vector

In [23]:
print(c[2])

tensor(5.)


#### Accessing element in a higher dimension Tensor 

To access one particular element in a tensor, we will need to specify indices equal to the dimension of the tensor. 

In [25]:
# All indices starting from 0
 
# Get element at row 1, column 0
print(f[1,0])

# We can also use the following
print(f[1][0])
 
# Similarly for 3D Tensor
print(g[1,0,0])
print(g[1][0][0])
 


tensor(3.)
tensor(3.)
tensor(5.)
tensor(5.)


In [39]:
# If you want to access one entire row in a 2D tensor, the syntax is same as NumPy 

# All elements 
print(f[:])

# All elements from index 1 to 2 (inclusive) 
print(c[1:3])

# All elements till index 3 (exclusive)
print(c[:3])


# First row
print(f[0,:])
 
# Second column
print(f[:,1])



tensor([[1., 2.],
        [3., 4.]])
tensor([3., 5.])
tensor([1., 3., 5.])
tensor([1., 2.])
tensor([2., 4.])


#### Specify data type of elements



In [40]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)
 
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
 
print(int_tensor)
     
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)

 
print(int_tensor)


torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Tensor to/from Numpy Array 

Can we convert to/from Pytorch Tensors and Numpy Arrays ? 


In [51]:
import numpy as np

# Tensor to Array 

f_numpy = f.numpy()
print(f_numpy)


# Array to Tensor 

h = np.array([[8,7,6,5], [1,2,3,4]])
h_tensor = torch.from_numpy(h)

print(h_tensor)



[[1. 2.]
 [3. 4.]]
tensor([[8, 7, 6, 5],
        [1, 2, 3, 4]], dtype=torch.int32)


#### Arithmetic Operations on Tensors

In [75]:
# lets create some tensors 
tensor1 = torch.tensor([[1,2,3], [4,5,6], [7,8,9] ]) 
tensor2 = torch.tensor([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])


# Addition 
print(tensor1 + tensor2)
#OR 
print(torch.add(tensor1, tensor2))


# Subtraction: 
print(tensor1 - tensor2)
# OR 
print(torch.sub(tensor1, tensor2))


# Multiplication:  

# Tensor with scalar 
print(tensor1*3)
print(2.5*tensor2)


# Tensor with Tensor 

# Element wise
print(tensor1*tensor2)

# Matrix Multiplication 
tensor3 = torch.mm(tensor1, tensor2)
print(tensor3)




# Division: 

# Tensor with Scalar 
print(tensor1/2)


# Tensor with another Tensor
# Elementwise division 
print(tensor2/tensor1)




tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])
tensor([[ -2,  -4,  -6],
        [ -8, -10, -12],
        [-14, -16, -18]])
tensor([[ -1,  -4,  -9],
        [-16, -25, -36],
        [-49, -64, -81]])
tensor([[ -30,  -36,  -42],
        [ -66,  -81,  -96],
        [-102, -126, -150]])
tensor([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]])
tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])


#### CPU and GPU Tensors 

Pytorch has different implementations of Tensor for CPU and GPU. Every tensor can be converted to GPU in order to perform massively parallel, fast computations. All operations that will be performed on the tensor will be carried out using GPU-specific routines that come with PyTorch

In [79]:
# Create a tensor for CPU
tensor_cpu = torch.tensor([[1,2],[3,4],[5,6]], device = 'cpu')

# Create a tensor for GPU
tensor_gpu = torch.tensor([[1,2],[3,4],[5,6]], device = 'cuda')

In [81]:
# This uses CPU RAM
tensor_cpu = tensor_cpu * 5
 
# This uses GPU RAM
# Focus on GPU RAM Consumption
tensor_gpu = tensor_gpu * 5


# Move GPU tensor to CPU
tensor_gpu_cpu = tensor_gpu.to(device='cpu')
 
# Move CPU tensor to GPU
tensor_cpu_gpu = tensor_cpu.to(device='cuda')